# Generated by Django 6.1.1 on 2026-10-02 14:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "clock_type",
                    models.TextField(
                        choices=[("LED", "LED"), ("SWEEPING", "Sweeping")],
                        default="LED",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clock",
                "verbose_name_plural": "Clocks",
            },
        ),
    ]
