# Generated by Django 6.1.1 on 2026-10-02 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studioclock", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clock",
            options={
                "ordering": ["name"],
                "verbose_name": "Clock",
                "verbose_name_plural": "Clocks",
            },
        ),
    ]
