# Generated by Django 6.1.1 on 2026-10-02 18:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studioclock", "0002_alter_clock_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="clock",
            name="led_colour",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
