# Generated by Django 6.1.1 on 2026-10-02 18:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studioclock", "0003_clock_led_colour"),
    ]

    operations = [
        migrations.AddField(
            model_name="clock",
            name="led_background_colour",
            field=colorfield.fields.ColorField(
                default="#000000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
