# Generated by Django 6.1.1 on 2026-10-03 17:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studioclock", "0004_clock_led_background_colour"),
    ]

    operations = [
        migrations.AddField(
            model_name="clock",
            name="sweeping_background_colour",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="clock",
            name="sweeping_hour_hand_colour",
            field=colorfield.fields.ColorField(
                default="#000000", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="clock",
            name="sweeping_minute_hand_colour",
            field=colorfield.fields.ColorField(
                default="#000000", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="clock",
            name="sweeping_second_hand_colour",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
