# Generated by Django 6.1.1 on 2026-10-03 17:27

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studioclock", "0005_clock_sweeping_background_colour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clock",
            name="sweeping_stroke_colour",
            field=colorfield.fields.ColorField(
                default="#000000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
