# Generated by Django 6.1.1 on 2026-10-03 18:04

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studioclock", "0006_clock_sweeping_stroke_colour"),
    ]

    operations = [
        migrations.AddField(
            model_name="clock",
            name="background_colour",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="clock",
            name="foreground_colour",
            field=colorfield.fields.ColorField(
                default="#000000", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="clock",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
