# Generated by Django 6.1.1 on 2026-10-04 08:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "studioclock",
            "0007_clock_background_colour_clock_foreground_colour_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Font",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("family", models.TextField(unique=True)),
                (
                    "category",
                    models.TextField(
                        choices=[
                            ("SANS_SERIF", "Sans Serif"),
                            ("SERIF", "Serif"),
                            ("MONOSPACE", "Monospace"),
                        ],
                        default="SANS_SERIF",
                    ),
                ),
            ],
            options={
                "verbose_name": "Font",
                "verbose_name_plural": "Fonts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FontWeight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField()),
                ("name", models.TextField()),
                (
                    "font",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="studioclock.font",
                    ),
                ),
            ],
            options={
                "verbose_name": "Font Weight",
                "verbose_name_plural": "Font Weights",
                "ordering": ["font", "weight"],
                "unique_together": {("font", "weight")},
            },
        ),
        migrations.AddField(
            model_name="clock",
            name="font",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="studioclock.fontweight",
            ),
        ),
    ]
