# Generated by Django 6.1.1 on 2026-10-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studioclock", "0009_nowplaying_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="clock",
            name="weather_forecast",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="clock",
            name="weather_last_polled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clock",
            name="weather_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clock",
            name="weather_location",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clock",
            name="weather_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clock",
            name="weather_units",
            field=models.TextField(
                choices=[
                    ("celsius", "Celsius (°C)"),
                    ("fahrenheit", "Fahrenheit (°F)"),
                ],
                default="celsius",
            ),
        ),
    ]
